import type {Metadata} from "next";
import {GeistSans} from 'geist/font/sans';
import "./globals.css";
import {Header} from "@/components/header";
import {Toaster} from "sonner";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={`${GeistSans.className} flex flex-col w-screen h-dvh`}>
        <Toaster/>
        <Header/>
        {children}
        </body>
        </html>
    );
}
